// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTgK8DJi3rEcBLk95BadH81QFRGBAzBFg',
    appId: '1:208599616375:web:3406ac5ee4b24da78baf72',
    messagingSenderId: '208599616375',
    projectId: 'cmsrgit',
    authDomain: 'cmsrgit.firebaseapp.com',
    databaseURL: 'https://cmsrgit-default-rtdb.firebaseio.com',
    storageBucket: 'cmsrgit.appspot.com',
    measurementId: 'G-9V44QE9N7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ29fnMBpUBA9frcPey2oX-0kw6Wc6Gig',
    appId: '1:208599616375:android:33aeea3ffb6ec7cd8baf72',
    messagingSenderId: '208599616375',
    projectId: 'cmsrgit',
    databaseURL: 'https://cmsrgit-default-rtdb.firebaseio.com',
    storageBucket: 'cmsrgit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEwjOWwsnBi5tdKVhKE9yyAyJQMnrMlIM',
    appId: '1:208599616375:ios:9428ee04902e3a328baf72',
    messagingSenderId: '208599616375',
    projectId: 'cmsrgit',
    databaseURL: 'https://cmsrgit-default-rtdb.firebaseio.com',
    storageBucket: 'cmsrgit.appspot.com',
    androidClientId: '208599616375-1gi3osjpfc0l5nq1tjtev7rek2587hjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEwjOWwsnBi5tdKVhKE9yyAyJQMnrMlIM',
    appId: '1:208599616375:ios:9428ee04902e3a328baf72',
    messagingSenderId: '208599616375',
    projectId: 'cmsrgit',
    databaseURL: 'https://cmsrgit-default-rtdb.firebaseio.com',
    storageBucket: 'cmsrgit.appspot.com',
    androidClientId: '208599616375-1gi3osjpfc0l5nq1tjtev7rek2587hjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCmCkoLGBra8-vpBKfkvdOhTroXZqCARo',
    appId: '1:208599616375:web:3be1d1e6644fc4438baf72',
    messagingSenderId: '208599616375',
    projectId: 'cmsrgit',
    authDomain: 'cmsrgit.firebaseapp.com',
    databaseURL: 'https://cmsrgit-default-rtdb.firebaseio.com',
    storageBucket: 'cmsrgit.appspot.com',
    measurementId: 'G-KNGCPVKG82',
  );
}
